---
- hosts: localhost
  gather_facts: false
  vars:
    state: present
  tasks:
  - name: Create cifs_server
    na_ontap_cifs_server:
      state: "{{ state }}"
      name: "{{ vserver|upper }}"
      vserver: "{{ vserver }}"
      service_state: started
      domain: "{{ domain }}"
      admin_user_name: "{{ domain_login }}"
      admin_password: "{{ domain_pwd }}"
      hostname: "{{ cluster_mgmt_lif }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false