---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: add subnet range
    na_ontap_command:
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      hostname: "{{ cluster_mgmt_lif }}"
      command: ['network', 'subnet', 'add-ranges', '-subnet-name', "{{ subnet_name }}", '-ipspace', "{{ ipspace }}", '-ip-ranges', "{{ ip_address }}"  ]
      privilege: admin
      use_rest: Always
      https: true
      validate_certs: false  