---
- hosts: localhost
  name: ONTAP
  gather_facts: false
  vars:
   state: present
  tasks:
  - name: "{{ tower_job_template_name }}"
    na_ontap_volume:
     state: "{{ state }}"
     name: "{{ volname }}"
     aggregate_name: "{{ aggr_name }}"
     size: "{{ size }}"
     size_unit: gb
     junction_path: "/{{ volname | replace('_','-') }}"
     space_guarantee: "none"
     volume_security_style: ntfs
     wait_for_completion: true
     vserver: "{{ vserver }}"
     hostname: "{{ cluster_mgmt_lif}}"
     username: "{{ netapp_username }}"
     password: "{{ netapp_password }}"
     https: true
     validate_certs: false