---
- hosts: localhost
  gather_facts: false
  vars:
    state: present
  tasks:
  - name: Create Vserver
    na_ontap_svm:
     state: present
     name: "{{ vserver }}"
     root_volume: "rt_{{ vserver }}_sys"
     root_volume_aggregate: "{{ aggr_name }}"
     root_volume_security_style: "{{ root_volume_security_style}}"
     allowed_protocols: "{{ allowed_protocols }}"
     comment: "{{ vserver_comment }}"
     ipspace: "{{ ipspace }}"
     hostname: "{{ cluster_mgmt_lif }}"
     username: "{{ netapp_username }}"
     password: "{{ netapp_password }}"
     https: true
     validate_certs: false